version: '3'
services:
  nginx:
    build:
      context: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - /home/spicyi/data/wordpress:/var/www/wordpress
    depends_on:
      - wordpress

  wordpress:
    build:
      context: ./requirements/wordpress
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=TETRIS@MDB
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - /home/spicyi/data/wordpress:/var/www/wordpress
    depends_on:
      - mariadb

  mariadb:
    build:
      context: ./requirements/mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=TETRIS@MDB
      - MYSQL_DATABASE=wordpress
    volumes:
      - /home/spicyi/data/mariadb:/var/lib/mysql

