version: '3'
services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - /home/spicyi/data/wordpress:/var/www/wordpress
    depends_on:
      - wordpress

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    env_file:
      - .env
    volumes:
      - /home/spicyi/data/wordpress:/var/www/wordpress
    depends_on:
      - mariadb

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/spicyi/data/mariadb
      o: bind