version: '3'

services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      - wordpress
      - adminer
      - redis
    restart: always
    networks:
      - inception

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      - mariadb
    restart: always
    networks:
      - inception

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
    networks:
      - inception
   
  adminer:
    container_name: adminer
    build:
      context: ./requirements/bonus/adminer
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      - mariadb
      - wordpress
    restart: always
    networks:
      - inception

  redis:
    container_name: redis
    build:
      context: ./requirements/bonus/redis
    volumes:
      - wordpress:/var/www/wordpress
    restart: always
    networks:
      - inception

  ftp:
    container_name: ftp
    build:
      context: ./requirements/bonus/ftp
    volumes:
      - wordpress:/home/tuna/ftp_directory/ftp_data
    ports:
      - "21:21"
    depends_on:
      - wordpress
    restart: always

  hugo:
    container_name: hugo
    build:
      context: ./requirements/bonus/hugo
    ports:
      - "1313:1313"
    restart: always


volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/spicyi/data/mariadb
      o: bind

  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/spicyi/data/wordpress
      o: bind


networks:
  inception:
    driver: bridge
