version: '3'
services:
  nginx:
    build:
      context: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - /home/spicyi/data/wordpress:/var/www/wordpress
    depends_on:
      - wordpress

  wordpress:
    build:
      context: ./requirements/wordpress
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=GAME_MASTER
      - WORDPRESS_DB_PASSWORD=TETRIS@MDB
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - /home/spicyi/data/wordpress:/var/www/wordpress
    depends_on:
      - mariadb

  mariadb:
    build:
      context: ./requirements/mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=GAME_MASTER
      - MYSQL_PASSWORD=TETRIS@MDB
      - MYSQL_DATABASE=wordpress
    volumes:
      - mariadb:/var/lib/mysql

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/spicyi/data/mariadb
      o: bind