FROM debian:bullseye

ENV MYSQL_ROOT_PASSWORD=TETRIS@MDB \
      MYSQL_DATABASE=wordpress

RUN apt-get update && apt-get install -y mariadb-server

COPY ./tools/config.sh .

COPY ./conf/mariadb.cnf /etc/mysql/my.cnf
RUN chmod +x config.sh

RUN   chown -R mysql:mysql /var/lib/mysql

EXPOSE 3306

ENTRYPOINT [ "./config.sh" ]