# This Dockerfile installs and configures MariaDB server on a Debian Bullseye image.
# It copies the config.sh script and mariadb.cnf configuration file to the container.
# The script is made executable and set as the entrypoint.
# Port 3306 is exposed for external access.

FROM debian:bullseye

ENV MYSQL_ROOT_PASSWORD=TETRIS@MDB \
      MYSQL_DATABASE=wordpress

RUN apt-get update && apt-get install -y mariadb-server

COPY ./tools/config.sh .

COPY ./conf/mariadb.cnf /etc/mysql/my.cnf

RUN chmod +x config.sh



EXPOSE 3306

ENTRYPOINT [ "./config.sh" ]