# vsftpd container for wordpress


FROM debian:bullseye

EXPOSE 21

RUN apt-get update && apt-get install -y vsftpd

COPY ./tools/ftp_entrypoint.sh ftp_entrypoint.sh

COPY ./conf/vsftpd.conf /vsftpd.conf


RUN chmod +x ftp_entrypoint.sh

ENTRYPOINT ["./ftp_entrypoint.sh"]