FROM debian:bullseye


# Install packages and clean cache

EXPOSE 9000

RUN apt-get update && apt-get -y install curl  &&\
    apt-get install -y php7.4-fpm php7.4-mysql \
    php7.4-curl php7.4-gd php7.4-intl php7.4-mbstring \
    php7.4-soap php7.4-xml php7.4-xmlrpc php7.4-zip &&\
    apt-get install -y mariadb-client

RUN curl -L -o adminer.php https://github.com/vrana/adminer/releases/download/v4.8.1/adminer-4.8.1.php 

RUN mkdir -p /var/www/wordpress && \
    mkdir -p /run/php

RUN chown -R 755 /var/www/wordpress

COPY ./tools/adminer_entrypoint.sh . 

RUN chmod +x adminer_entrypoint.sh

ENTRYPOINT [ "/adminer_entrypoint.sh" ]